In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [3]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
#transformeers-> OrdinalEncoder,OneHotEncoder,SimpleImputer

In [5]:
df.isnull().sum()

Age          0
Job          0
Marital      0
Education    0
Default      0
Balance      0
Housing      0
Loan         0
contact      0
Day          0
Month        0
Duration     0
Campaign     0
Pdays        0
Previous     0
poutcome     0
TARGET       0
dtype: int64

In [6]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer

In [7]:
df.columns

Index(['Age', 'Job', 'Marital', 'Education', 'Default', 'Balance', 'Housing',
       'Loan', 'contact', 'Day', 'Month', 'Duration', 'Campaign', 'Pdays',
       'Previous', 'poutcome', 'TARGET'],
      dtype='object')

In [8]:
#tranformer=ColumnTransformer(transformers=[(),()],remainder='passthrough')
transformer=ColumnTransformer(transformers=[('tr1',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']]),['Education',] ),('tr2',OneHotEncoder(),['Job','Marital','Default','Housing','Loan','contact','Month','poutcome'])],remainder='passthrough')

In [23]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('tr1',
                                 OrdinalEncoder(categories=[['unknown',
                                                             'primary',
                                                             'secondary',
                                                             'tertiary']]),
                                 ['Education']),
                                ('tr2', OneHotEncoder(),
                                 ['Job', 'Marital', 'Default', 'Housing',
                                  'Loan', 'contact', 'Month', 'poutcome'])])

In [10]:
X=df.iloc[:,:-1]

In [11]:
X

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other

In [12]:
Y=df['TARGET']

In [13]:
Y

0         no
1         no
2         no
3         no
4         no
        ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: TARGET, Length: 45211, dtype: object

In [14]:
X=transformer.fit_transform(X)

In [15]:
X

array([[  3.,   0.,   0., ...,   1.,  -1.,   0.],
       [  2.,   0.,   0., ...,   1.,  -1.,   0.],
       [  2.,   0.,   0., ...,   1.,  -1.,   0.],
       ...,
       [  2.,   0.,   0., ...,   5., 184.,   3.],
       [  2.,   0.,   1., ...,   4.,  -1.,   0.],
       [  2.,   0.,   0., ...,   2., 188.,  11.]], shape=(45211, 48))

In [16]:
le=LabelEncoder()
Y=le.fit_transform(Y)

In [17]:
Y

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
ss=StandardScaler()

In [20]:
scaled_X=ss.fit_transform(X)

In [21]:
scaled_X

array([[ 1.20648448, -0.35936869, -0.52373954, ..., -0.56935064,
        -0.41145311, -0.25194037],
       [-0.07771493, -0.35936869, -0.52373954, ..., -0.56935064,
        -0.41145311, -0.25194037],
       [-0.07771493, -0.35936869, -0.52373954, ..., -0.56935064,
        -0.41145311, -0.25194037],
       ...,
       [-0.07771493, -0.35936869, -0.52373954, ...,  0.72181052,
         1.43618859,  1.05047333],
       [-0.07771493, -0.35936869,  1.909346  , ...,  0.39902023,
        -0.41145311, -0.25194037],
       [-0.07771493, -0.35936869, -0.52373954, ..., -0.24656035,
         1.4761376 ,  4.52357654]], shape=(45211, 48))

In [22]:
Y

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))