In [1]:
import pandas as pd

In [2]:
bank=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [3]:
bank.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [4]:
bank['Job'].value_counts()

Job
blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: count, dtype: int64

In [5]:
bank['Education'].value_counts()

Education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [6]:
#tertiary> secondary> primary>unknown

In [7]:
#ordinal column -> education column-> OrdinalEncoder
#label encoder -> target column--> LabelEncoder
#nominal column-> married.,...

#column transformer is for complete dataframe no need to seggregate nomina,label or ordinal encoder

In [8]:
ordinal_data=bank[['Education']]

In [9]:
ordinal_data

       Education
0       tertiary
1      secondary
2      secondary
3        unknown
4        unknown
...          ...
45206   tertiary
45207    primary
45208  secondary
45209  secondary
45210  secondary

[45211 rows x 1 columns]

In [10]:
target_data=bank['TARGET']

In [11]:
target_data

0         no
1         no
2         no
3         no
4         no
        ...
45206    yes
45207    yes
45208    yes
45209     no
45210     no
Name: TARGET, Length: 45211, dtype: object

In [12]:
from sklearn.preprocessing import OrdinalEncoder

In [15]:
oe=OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])

In [16]:
ordinal_data=oe.fit_transform(ordinal_data)

In [18]:
ordinal_data

array([[3.],
       [2.],
       [2.],
       ...,
       [2.],
       [2.],
       [2.]], shape=(45211, 1))

In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
le=LabelEncoder()

In [21]:
target_data=le.fit_transform(target_data)

In [23]:
target_data

array([0, 0, 0, ..., 1, 0, 0], shape=(45211,))

In [24]:
#nominal encoder=one hot encoder
nominal_data=bank[['Job','Marital','Education','Default','Housing','Loan','contact','Month','poutcome']]

In [25]:
nominal_data

,Job,Marital,Education,Default,Housing,Loan,contact,Month,poutcome
0,management,married,tertiary,no,yes,no,unknown,may,unknown
1,technician,single,secondary,no,yes,no,unknown,may,unknown
2,entrepreneur,married,secondary,no,yes,yes,unknown,may,unknown
3,blue-collar,married,unknown,no,yes,no,unknown,may,unknown
4,unknown,single,unknown,no,no,no,unknown,may,unknown
...,...,...,...,...,...,...,...,...,...
45206,technician,married,tertiary,no,no,no,cellular,nov,unknown
45207,retired,divorced,primary,no,no,no,cellular,nov,unknown
45208,retired,married,secondary,no,no,no,cellular,nov,success
45209,blue-collar,married,secondary,no,no,no,telephone,nov,unknown
45210,entrepreneur,married,secondary,no,no,no,cellular,nov,other

In [26]:
bank['Marital'].value_counts()

Marital
married     27214
single      12790
divorced     5207
Name: count, dtype: int64

In [28]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [29]:
nominal_data=ohe.fit_transform(nominal_data)

In [30]:
nominal_data

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 406899 stored elements and shape (45211, 44)>

In [ ]:
#column transformer -> most important
''' This transformer can help us in transforming ordinal data, nominal data and numeric data '''