In [1]:
#4 march 2026
import pandas as pd

In [2]:
df=pd.read_csv('Bank_Marketing_Original_Data.csv')

In [3]:
df.head()

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome,TARGET
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [5]:
#first step -> separate data in multiple data categories
numeric_data=['Age','Balance','Day','Duration','Campaign','Pdays','Previous']

ordinal_data=['Education']

nominal_data=['Job','Marital','Default','Housing','Loan','contact','Month','poutcome']

In [6]:
numeric_data

['Age', 'Balance', 'Day', 'Duration', 'Campaign', 'Pdays', 'Previous']

In [7]:
# separate pipeline transformer for our separate data
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [8]:
# since column data is numeric hence no encdoing is not needed only StandardScalar()
numeric_pipeline=Pipeline(steps=[('imputer',SimpleImputer(strategy='mean')),('scaling',StandardScaler())])

In [9]:
numeric_pipeline

Pipeline(steps=[('imputer', SimpleImputer()), ('scaling', StandardScaler())])

In [10]:
ordinal_pipeline=Pipeline(steps=[('imputer',SimpleImputer(strategy='most_frequent')),('encoding',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])),('scaling',StandardScaler())])

In [11]:
ordinal_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoding',
                 OrdinalEncoder(categories=[['unknown', 'primary', 'secondary',
                                             'tertiary']])),
                ('scaling', StandardScaler())])

In [12]:
#scanling is not needed as OneHotEncoder convert the data into 0 and 1 hence scaling is not needed.

nominal_pipeline=Pipeline(steps=[('imputer',SimpleImputer(strategy='most_frequent')),('encoding',OneHotEncoder(handle_unknown='ignore'))])

In [13]:
# third step
"""combine pipeline transformer with thier respective data"""
from sklearn.compose import ColumnTransformer

In [14]:
feature=ColumnTransformer(transformers=[('numeric transformation',numeric_pipeline,numeric_data),('ordinal transformation',ordinal_pipeline,ordinal_data),('nominal tranformation',nominal_pipeline,nominal_data)])

In [15]:
feature

ColumnTransformer(transformers=[('numeric transformation',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['Age', 'Balance', 'Day', 'Duration',
                                  'Campaign', 'Pdays', 'Previous']),
                                ('ordinal transformation',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OrdinalEncoder(categories=[['unknown',
                                                                              'primary',
                                                                              'secondary',
                                                                              'tertiary']])),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['Education']),
                                ('nominal tranformation',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['Job', 'Marital', 'Default', 'Housing',
                                  'Loan', 'contact', 'Month', 'poutcome'])])

In [16]:
#fourth step- create an model with the respective transformer along with their algorith
from sklearn.linear_model import LogisticRegression

In [17]:
model=Pipeline(steps=[('feature',feature),('classifier',LogisticRegression())])

In [18]:
model

Pipeline(steps=[('feature',
                 ColumnTransformer(transformers=[('numeric transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Age', 'Balance', 'Day',
                                                   'Duration', 'Campaign',
                                                   'Pdays', 'Previous']),
                                                 ('ordinal transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OrdinalEncoder(categ...nown',
                                                                                               'primary',
                                                                                               'secondary',
                                                                                               'tertiary']])),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Education']),
                                                 ('nominal tranformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Job', 'Marital', 'Default',
                                                   'Housing', 'Loan', 'contact',
                                                   'Month', 'poutcome'])])),
                ('classifier', LogisticRegression())])

In [19]:
#fifth step-> train test split my data and encoding of my output column data
from sklearn.model_selection import train_test_split

In [20]:
X=df.iloc[:,:-1]
Y=df['TARGET']

In [22]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [23]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)

In [25]:
x_train

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome
17961,54,retired,single,secondary,no,10621,no,no,cellular,30,jul,187,2,-1,0,unknown
9504,37,blue-collar,divorced,secondary,no,33,yes,no,unknown,6,jun,326,1,-1,0,unknown
37849,25,student,single,tertiary,no,938,yes,no,cellular,14,may,36,1,352,1,other
22777,30,management,married,tertiary,no,144,yes,no,cellular,25,aug,23,17,-1,0,unknown
1168,34,management,married,primary,no,6,yes,no,unknown,8,may,125,3,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,36,admin.,married,secondary,no,639,yes,no,unknown,6,may,191,1,-1,0,unknown
43753,61,admin.,married,unknown,no,1088,yes,no,cellular,20,may,254,1,359,1,failure
36210,43,services,single,tertiary,no,553,no,no,cellular,11,may,323,1,-1,0,unknown
39227,37,blue-collar,married,secondary,no,-83,yes,no,cellular,18,may,179,4,-1,0,unknown
23600,51,services,married,unknown,no,7175,no,no,cellular,28,aug,98,14,-1,0,unknown

In [26]:
y_train

array([0, 0, 0, ..., 0, 0, 0], shape=(36168,))

In [28]:
y_test

array([0, 0, 0, ..., 0, 0, 1], shape=(9043,))

In [27]:
x_test

,Age,Job,Marital,Education,Default,Balance,Housing,Loan,contact,Day,Month,Duration,Campaign,Pdays,Previous,poutcome
6327,36,management,married,tertiary,no,0,yes,no,unknown,27,may,145,2,-1,0,unknown
23911,59,technician,divorced,secondary,no,2595,yes,no,cellular,29,aug,398,2,-1,0,unknown
39245,28,technician,single,secondary,no,-16,yes,no,cellular,18,may,251,3,-1,0,unknown
16841,25,services,married,secondary,no,0,yes,no,cellular,24,jul,458,9,-1,0,unknown
941,47,blue-collar,married,secondary,yes,-5,yes,no,unknown,7,may,444,1,-1,0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27372,43,management,married,tertiary,no,2083,no,no,cellular,21,nov,120,2,-1,0,unknown
22645,50,services,married,secondary,no,26394,no,no,cellular,25,aug,206,4,-1,0,unknown
26448,35,blue-collar,married,secondary,no,667,no,no,cellular,20,nov,178,1,-1,0,unknown
25888,43,blue-collar,married,primary,no,12618,yes,no,cellular,19,nov,25,1,-1,0,unknown
4719,35,blue-collar,married,unknown,no,4822,yes,no,unknown,20,may,843,2,-1,0,unknown

In [24]:
# final step-> model training and getting prediction from the model
model.fit(x_train,y_train)

Pipeline(steps=[('feature',
                 ColumnTransformer(transformers=[('numeric transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Age', 'Balance', 'Day',
                                                   'Duration', 'Campaign',
                                                   'Pdays', 'Previous']),
                                                 ('ordinal transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OrdinalEncoder(categ...nown',
                                                                                               'primary',
                                                                                               'secondary',
                                                                                               'tertiary']])),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Education']),
                                                 ('nominal tranformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Job', 'Marital', 'Default',
                                                   'Housing', 'Loan', 'contact',
                                                   'Month', 'poutcome'])])),
                ('classifier', LogisticRegression())])

In [29]:
y_predict=model.predict(x_test)

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

0.9005860886873825

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
model=Pipeline(steps=[('feature',feature),('classifier',RandomForestClassifier())])

In [33]:
model

Pipeline(steps=[('feature',
                 ColumnTransformer(transformers=[('numeric transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Age', 'Balance', 'Day',
                                                   'Duration', 'Campaign',
                                                   'Pdays', 'Previous']),
                                                 ('ordinal transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OrdinalEncoder(categ...',
                                                                                               'primary',
                                                                                               'secondary',
                                                                                               'tertiary']])),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Education']),
                                                 ('nominal tranformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Job', 'Marital', 'Default',
                                                   'Housing', 'Loan', 'contact',
                                                   'Month', 'poutcome'])])),
                ('classifier', RandomForestClassifier())])

In [34]:
model.fit(x_train,y_train)

Pipeline(steps=[('feature',
                 ColumnTransformer(transformers=[('numeric transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Age', 'Balance', 'Day',
                                                   'Duration', 'Campaign',
                                                   'Pdays', 'Previous']),
                                                 ('ordinal transformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OrdinalEncoder(categ...',
                                                                                               'primary',
                                                                                               'secondary',
                                                                                               'tertiary']])),
                                                                  ('scaling',
                                                                   StandardScaler())]),
                                                  ['Education']),
                                                 ('nominal tranformation',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoding',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Job', 'Marital', 'Default',
                                                   'Housing', 'Loan', 'contact',
                                                   'Month', 'poutcome'])])),
                ('classifier', RandomForestClassifier())])

In [35]:
#model.fit(x_train,y_train)
y_predict=model.predict(x_test)
accuracy_score(y_test,y_predict)

0.9032400751962845